-- Create the gallery table
create table public.gallery (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  location text,
  category text not null,
  type text default 'image',
  src text not null
);

-- Enable Row Level Security
alter table public.gallery enable row level security;

-- Create policies
create policy "Enable read access for all users"
on public.gallery for select
using (true);

create policy "Enable insert for authenticated users only"
on public.gallery for insert
to authenticated
with check (true);

create policy "Enable update for authenticated users only"
on public.gallery for update
to authenticated
using (true)
with check (true);

create policy "Enable delete for authenticated users only"
on public.gallery for delete
to authenticated
using (true);

-- Insert dummy data (migrated from Gallery.tsx)
insert into public.gallery (title, location, category, type, src)
values 
  ('Children Playing', 'N''Djari', 'field', 'image', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=2070&auto=format&fit=crop'),
  ('School Distribution', 'Gassi', 'education', 'image', 'https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=2070&auto=format&fit=crop'),
  ('Medical Checkup', 'Hospital Ref', 'health', 'image', 'https://images.unsplash.com/photo-1576091160550-217358c7e618?q=80&w=2070&auto=format&fit=crop'),
  ('Community Meeting', 'Farcha', 'field', 'image', 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=2013&auto=format&fit=crop'),
  ('Classroom Session', 'Unknown', 'education', 'image', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=2132&auto=format&fit=crop'),
  ('Charity Event', 'N''Djamena', 'events', 'video', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=2070&auto=format&fit=crop'),
  ('Vaccination Drive', 'Moursal', 'health', 'image', 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?q=80&w=2032&auto=format&fit=crop'),
  ('Food Distribution', 'Walia', 'field', 'image', 'https://images.unsplash.com/photo-1594708767771-a7502209ff51?q=80&w=2080&auto=format&fit=crop'),
  ('Cultural Fest', 'Palais', 'events', 'image', 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?q=80&w=2070&auto=format&fit=crop');
