-- Create the news table
create table public.news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  category text not null,
  date text, -- Storing as string for simplicity to match UI, or use date type
  type text default 'article',
  excerpt text,
  image text,
  "linkKey" text default 'more'
);

-- Enable Row Level Security
alter table public.news enable row level security;

-- Create policies
create policy "Enable read access for all users"
on public.news for select
using (true);

create policy "Enable insert for authenticated users only"
on public.news for insert
to authenticated
with check (true);

create policy "Enable update for authenticated users only"
on public.news for update
to authenticated
using (true)
with check (true);

create policy "Enable delete for authenticated users only"
on public.news for delete
to authenticated
using (true);

-- Insert some dummy data to start with (matching the hardcoded data)
insert into public.news (title, category, date, type, excerpt, image, "linkKey")
values 
  ('1 Year Serving Humanitarian Action', 'event', 'March 2024', 'article', 'Association Actions Pour Tous celebrates its first year of existence. A year rich in emotions, solidarity, and concrete actions for Chad.', '/assets/images/facebook/anniversary.png', 'report'),
  ('Highlights: Community Dinner Sharing', 'solidarity', 'February 2024', 'video', 'Looking back at our grand charity dinner. More than 200 meals distributed in an atmosphere of fraternity and sharing.', '/assets/images/facebook/dinner.png', 'video'),
  ('Sanitation at SOS N''Djari Health Center', 'health', 'November 2023', 'article', 'Our volunteers mobilized for a day of cleaning and disinfection at the health center, ensuring a healthy environment for patients.', '/assets/images/facebook/sanitation.png', 'article');
